---
title: "Attrition-Commuting"
author: "AMarkum"
date: "3/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Correlates Attrition with distance Commuted
Part of a deeper look at why people leave:

```{r}
# Calculate average Distance for employees who stay
# Create a new column for employees who quit
# Compare commute Distances between current and former employees
options(repr.plot.width=8, repr.plot.height=4)

no.attritions <- df %>% filter(Attrition == "No")

# Average distance of employees that didn't quit.
med.distance <- no.attritions %>% select(DistanceFromHome) %>% summarize(med.dist=round(median(DistanceFromHome), 2))

attritions$Median_Distance <- ifelse(attritions$DistanceFromHome < 7, "Below Average", "Above Average")

# Distribution of Distance vs. Work Status
dist <- attritions %>% select(Median_Distance, DistanceFromHome) %>%
ggplot(aes(x=DistanceFromHome, fill=Median_Distance)) + geom_density() + facet_wrap(~Median_Distance) + theme_minimal() + 
scale_color_manual(values=c("#2EFE64", "#FA5858")) + scale_fill_manual(values=c("#F6CED8", "#ECF6CE")) +
theme(legend.position="bottom", plot.background=element_rect(fill="#FFF1E0")) + 
geom_vline(aes(xintercept=7),
            color="black", linetype="dashed", size=1) + 
annotate("text", label = "Median = 7", x = 15, y = 0.17, color = "black")

dist
```
