---
title: "Causal-Income_Attrition"
author: "AMarkum"
date: "3/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chart helps to answer the question whether income is a primary reason for attrition

code provides a visual representation of whether satisfaction with income levels affects attrition rates:

```{r}
options(repr.plot.width=8, repr.plot.height=5) 

# Make sure your column is identified as a factor - doesn't work otherwise

df$JobSatisfaction <- as.factor(df$JobSatisfaction)

high.inc <- df %>% select(JobSatisfaction, MonthlyIncome, Attrition) %>% group_by(JobSatisfaction, Attrition) %>%
summarize(med=median(MonthlyIncome)) %>%
ggplot(aes(x=fct_reorder(JobSatisfaction, -med), y=med, color=Attrition)) + 
  geom_point(size=3) + 
  geom_segment(aes(x=JobSatisfaction, 
                   xend=JobSatisfaction, 
                   y=0, 
                   yend=med)) + facet_wrap(~Attrition) + 
  labs(title="Is Income a Reason for Employees to Leave?", 
       subtitle="by Attrition Status",
      y="Median Income",
      x="Level of Job Satisfaction") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6), plot.title=element_text(hjust=0.5), strip.background = element_blank(),
  strip.text = element_blank()) + 
coord_flip() + theme_minimal() + scale_color_manual(values=c("#58FA58", "#FA5858")) + 
geom_text(aes(x=JobSatisfaction, y=0.01, label= paste0("$ ", round(med,2))),
            hjust=-0.5, vjust=-0.5, size=4, 
            colour="black", fontface="italic",
         angle=360)


high.inc
```
