---
title: "DataSplitting"
author: "AMarkum"
date: "3/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Splitting the Data for Training & Testing

This file splits the data into testing and training portions:

```{r}
set.seed(142)
original_df <- original_df[sample(nrow(original_df)),]

# Encode the ordinal variables
original_df$BusinessTravel = factor(original_df$BusinessTravel,
                         levels = c('Travel_Frequently', 'Travel_Rarely', 'Non-Travel'),
                         labels = c(1, 2, 3))

# Change the datatype from integer to factors from the ordinal variables.
cols <- c("Education", "EnvironmentSatisfaction", "JobInvolvement", "JobLevel",
         "JobSatisfaction", "PerformanceRating", "RelationshipSatisfaction", 
         "StockOptionLevel", "TrainingTimesLastYear", "WorkLifeBalance")

original_df[cols] <- lapply(original_df[cols], factor)

# Delete unecessary columns
cols <- c("Over18", "EmployeeNumber", "EmployeeCount")

original_df[cols] <- NULL

# Split the data
trainIndex <- createDataPartition(original_df$Attrition, p=0.8, 
                                 list=FALSE, times=1)
train <- original_df[trainIndex,]
test <- original_df[-trainIndex,]

# Check that training and testing sets have the same label proportions
prop_train <- train %>% select(Attrition) %>% group_by(Attrition) %>% summarize(n=n()) %>%
mutate(pct=round(prop.table(n), 2))

prop_test <- test %>% select(Attrition) %>% group_by(Attrition) %>% summarize(n=n()) %>%
mutate(pct=round(prop.table(n), 2))


# Split into the features and labels X_train and y_train
X_train <- train[,-2]
y_train <- train["Attrition"]

##Split the Testing sets into features and label
X_test <- test[,-2]
y_test <- test["Attrition"]

dmy <- dummyVars("~.", data=original_df)
new <- data.frame(predict(dmy, newdata=original_df, levelsOnly=True))

prop_train
prop_test

options(repr.plot.width=10, repr.plot.height=8) 

rpart.tree <- rpart(Attrition ~ ., data=train)
plot(rpart.tree, uniform=TRUE, branch=0.6, margin=0.05)
text(rpart.tree, all=TRUE, use.n=TRUE)
title("Training Set's Classification Tree")

# Pruning eliminates things that don't provide power to classify intsances
prune.rpart.tree <- prune(rpart.tree, cp=0.02) 
plot(prune.rpart.tree, uniform=TRUE, branch=0.6)
text(prune.rpart.tree, all=TRUE, use.n=TRUE)

library(partykit)

rparty.tree <- as.party(rpart.tree)
rparty.tree

options(repr.plot.width=12, repr.plot.height=12) 

fancyRpartPlot(rpart.tree)

numerics_df <- select_if(train, is.numeric)
numerics_scaled <- preProcess(train, method = c("center", "scale"))
trainTransformed <- predict(numerics_scaled, train)
trainTransformed
```
