---
title: "Income-Department"
author: "AMarkum"
date: "3/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Income Levels by Department

Identifies average income levels per department, comparing income of people leaving the company to the incomes of those who stay. Helps to determine whether income was a major factor when leaving the company.:

```{r}

# Group by department 
options(repr.plot.width=8, repr.plot.height=5) 

avg.income <- df %>% select(Department, MonthlyIncome, Attrition) %>% group_by(Attrition, Department) %>%
summarize(avg.inc=mean(MonthlyIncome)) %>%
ggplot(aes(x=reorder(Department, avg.inc), y=avg.inc, fill=Attrition)) + geom_bar(stat="identity", position="dodge") + facet_wrap(~Attrition) + 
theme_minimal() + theme(axis.text.x = element_text(angle = 90), plot.title=element_text(hjust=0.5)) + 
scale_fill_manual(values=c("lightgreen", "tomato2")) + 
labs(y="Average Income", x="Department", title="Average Income by Department \n and Attrition Status") + 
geom_text(aes(x=Department, y=0.01, label= paste0("$ ", round(avg.inc,2))),
            hjust=-0.5, vjust=0, size=3, 
            colour="black", fontface="bold",
         angle=90)

avg.income
```
