---
title: "Managers-JobSatisfaction"
author: "AMarkum"
date: "3/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Comparing Time with Managers and Overall Satisfaction

These two charts help to identify if there is a correlation between length of time with a current Manager and Overall Satisfaction:

```{r}
# Create a Categorical Value for Years with Current Manager
# Create a Categorical Value for RelationShip Satisfaction
# Use income as Y-Axis
options(repr.plot.width=8, repr.plot.height=7)

df$CatYearsManager <- ifelse(df$YearsWithCurrManager <= 1, "Recently Hired",
                            ifelse(df$YearsWithCurrManager > 1 & df$YearsWithCurrManager <= 4, "2-4 Years hired", "Long Established Manager"))


# Correlate Average Relationship Satisfaction with Recently Hired Managers
rel.sat <- df %>% select(CatYearsManager, RelationshipSatisfaction, Attrition) %>% group_by(CatYearsManager, Attrition) %>%
summarize(avg.sat=mean(RelationshipSatisfaction)) %>%
ggplot(aes(x=fct_reorder(CatYearsManager,-avg.sat), y=avg.sat, fill=Attrition)) + geom_bar(stat="identity", position="dodge") + facet_wrap(~Attrition) + 
geom_text(aes(x=CatYearsManager, y=0, label= paste0(round(avg.sat,2))),
            hjust=-0.5, vjust=-0.5, size=4, 
            colour="black", fontface="italic",
         angle=360) + coord_flip() + theme_bw() + 
theme(legend.position="none", strip.background = element_blank(), strip.text.x = element_blank(), plot.title=element_text(hjust=0.5),
     axis.text.y = element_text(angle = 55)) + 
labs(x="Years with Current Manager",y="Average Satisfaction Score", title="Dealing with Current Managers") + 
scale_fill_manual(values=c("#58FA58", "#FA5858"))


# Create a Distribution by Attrition of the RelationShip Satisfaction
rel.dist <- df %>% select(RelationshipSatisfaction, Attrition) %>% group_by(Attrition) %>% 
ggplot(aes(x=RelationshipSatisfaction, y=..density..)) + geom_density(aes(fill=Attrition)) + facet_wrap(~Attrition) + 
theme_bw() + theme(legend.position="bottom", strip.background = element_blank(), strip.text.x = element_blank()) + 
scale_fill_manual(values=c("#58FA58", "#FA5858"))


plot_grid(rel.sat, rel.dist, nrow=2)
```
