---
title: "Salary_Department-Barcharts"
author: "AMarkum"
date: "3/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## File is for two bar charts providing information on Salaries and Department Gender Ratios

This chunk of code provides two bar charts: 1) Average salary broken out by gender and 2) number of employees by department:

```{r}
options(repr.plot.width=10, repr.plot.height=8) 

gender.income <- df %>% select(Gender, MonthlyIncome) %>% group_by(Gender) %>% summarise(avg_income=round(mean(MonthlyIncome), 2)) %>%
ggplot(aes(x=Gender, y=avg_income)) + geom_bar(stat="identity", fill="#2E9AFE", width=0.5) + 
geom_text(aes(x=Gender, y=0.01, label= paste0("$ ", avg_income)),
            hjust=-2, vjust=0, size=3, 
            colour="black", fontface="bold",
         angle=360) + labs(title="Average Salary by Gender", x="Gender",y="Salary") + coord_flip() + 
theme_minimal() + theme(plot.title=element_text(size=14, hjust=0.5))

# department by gender
gender.department <- df %>% group_by(Department, Gender) %>% summarise(amount=n()) %>%
ggplot(aes(x=reorder(Department, -amount), y=amount, fill=Gender)) + geom_bar(stat="identity", position="dodge") + theme_minimal() + 
theme(axis.text.x = element_text(angle = 90), plot.title=element_text(hjust=0.5)) + scale_fill_manual(values=c("pink", "lightblue")) + 
labs(title="Number of Employees \n
by Department",x="Department", y="Number of employees")

departments <- df %>% group_by(Department, Gender) %>% summarise(amount=n()) %>%
ggplot(aes(x="", y=amount, fill=Department), show.legend=FALSE, width=) + geom_bar(stat="identity", position="dodge") + theme_minimal() + 
theme(axis.text.x = element_text(angle = 90), plot.title=element_text(hjust=0.5), aspect.ratio=1) + 
labs(title="Number of Employees \n
by Department") + coord_polar() + scale_fill_manual(values=c("#FE642E", "#0080FF","#00FF40"))

plot_grid(gender.income, gender.department, departments, ncol=2, nrow=2)
```
